fix: added by pass for windows OS to properly convert negative timestamps into datetimes. build: removed testing actions

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -3,42 +3,47 @@ name: tests
 on:
   push:
     branches-ignore:
-      - 'v*'
+    - 'v*'
   pull_request:
 
 jobs:
   build:
-    if: github.repository == 'pabloitu/pycsep'
+    if: github.repository == 'SCECCode/pycsep'
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest, windows-latest]
-        python-version: ['3.10']
+        os: [ubuntu-latest, macos-latest]
+        python-version: ['3.7', '3.8', '3.9', '3.10']
     defaults:
       run:
         shell: bash -l {0}
 
     steps:
-      - uses: actions/checkout@v2
-      - uses: mamba-org/setup-micromamba@v1
-        with:
-          generate-run-shell: true
-          environment-file: requirements.yml
-          create-args: >-
-            python=${{ matrix.python-version }}
+    - uses: actions/checkout@v2
+    - uses: conda-incubator/setup-miniconda@v2
+      with:
+        python-version: ${{ matrix.python-version }}
+        activate-environment: csep-dev
+        channels: conda-forge
 
-      - name: Install pyCSEP
-        run: |
-          pip install --no-deps -e .
-          python -c "import csep; print('Version: ', csep.__version__)"
+    - name: Install dependencies
+      run: |
+        conda env update --file requirements.yml
+        conda info -a
+        conda list
 
-      - name: Test with pytest
-        run: |
-          pip install vcrpy==4.3.1 pytest pytest-cov
-          pytest --cov=./ --cov-config=.coveragerc
+    - name: Install pyCSEP
+      run: |
+        pip install --no-deps -e .
+        python -c "import csep; print('Version: ', csep.__version__)"
 
-      - name: Upload coverage
-        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
-        run: |
-          bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
+    - name: Test with pytest
+      run: |
+        conda install pytest-cov
+        pytest --cov=./ --cov-config=.coveragerc
+
+    - name: Upload coverage
+      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
+      run: |
+        bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
